ME1/1 ME1/2 2/X   3/X   4/X
5680, 6860, 7910, 9115, 10020 (mm)
5.68  6.86  7.91  9.115 10.020




In [134]:
from math import pi

from numpy import log, tan, cos, sin

tan in radian

In [128]:
z11 = 5.68
z12 = 6.86
z20 = 6.86
z30 = 7.91
z40 = 10.020

In [1]:
import sys
sys.path.append('./custom_modules/') 
import module1 as md
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
!cat configs/filepath.txt
X, y = md.load_input_file("/uscms_data/d3/mkim/MKWorkingArea/CMSSW_10_2_0/src/JL/Melrose/P2_CMSSW_10_1_5/src/L1TMuonSimulations/Analyzers/test7/histos_tba.20.npz")

fnal cmslpc computer cluster

/uscms_data/d3/mkim/MKWorkingArea/CMSSW_10_2_0/src/JL/Melrose/P2_CMSSW_10_1_5/src/L1TMuonSimulations/Analyzers/test7/histos_tba.20.npz
<class 'numpy.lib.npyio.NpzFile'>
['variables', 'parameters']


z*tan(theta)*cos(phi)

In [192]:
X0=X.astype(float)

In [163]:
tan(pi/4)

0.9999999999999999

In [193]:
X1 = X0.copy()

In [194]:
X1[:,:,0] = X0[:,:,0]*(1./16)*(pi/180)

In [195]:
X1[:,:,0]

array([[3.80045445, 3.63028484, 3.63028484, 3.66519143],
       [4.22696928, 4.37204978, 4.38950307, 4.39822972],
       [4.65675661, 4.38732141, 4.33714319, 4.28478331],
       ...,
       [4.28914664, 4.15170196, 4.11897703, 4.12770368],
       [2.70198785, 2.65290046, 2.64199216, 2.64417382],
       [4.72111563, 4.61639587, 4.58148929, 4.55530935]])

In [196]:
X2 = X1.copy()

In [197]:
X2[:,:,1] = (X1[:,:,1]*1./4+10)*(pi/180)

In [198]:
X2[:,:,1]

array([[0.3577925 , 0.35342917, 0.34906585, 0.34906585],
       [0.27488936, 0.27925268, 0.27488936, 0.27925268],
       [0.21816616, 0.21380283, 0.20943951, 0.20943951],
       ...,
       [0.283616  , 0.27488936, 0.27488936, 0.27488936],
       [0.23561945, 0.23125613, 0.23125613, 0.23125613],
       [0.21816616, 0.21380283, 0.21380283, 0.21380283]])

In [388]:
for i in range(1000):
    phi11 = X2[i,0,0]
    tht11 = X2[i,0,1]
    
    phi20 = X2[i,1,0]
    tht20 = X2[i,1,1]
    
    phi30 = X2[i,2,0]
    tht30 = X2[i,2,1]
    
    phi40 = X2[i,3,0]
    tht40 = X2[i,3,1]
    pt = round(1/y[i,0],1)
    print("pt: ",pt)
    l_x = [z11*tan(tht11)*cos(phi11), z20*tan(tht20)*cos(phi20), z30*tan(tht30)*cos(phi30), z40*tan(tht40)*cos(phi40)]
    l_y = [z11*tan(tht11)*sin(phi11), z20*tan(tht20)*sin(phi20), z30*tan(tht30)*sin(phi30), z40*tan(tht40)*sin(phi40)]
    l_z = [z11, z20, z30, z40]
    
    
    plt.scatter(l_x,l_y)
    plt.text(2,4, "pt: %s GeV"%pt, fontsize=12)
    plt.xlabel("x (M)")
    plt.ylabel("y (M)")
    plt.hlines(0,-5,5)
    plt.vlines(0,-5,5)
    plt.xlim(-5,5)
    plt.ylim(-5,5)
    print("pt: ",1/y[i,0])
    plt.savefig("im_xy_%d"%i)
    plt.clf()
    
    plt.scatter(l_z, l_x)
    plt.text(7,4, "pt: %s GeV"%pt, fontsize=12)
    plt.xlabel("z (M)")
    plt.ylabel("x (M)")
    plt.hlines(0,0,10)
    plt.xlim(0,10)
    plt.ylim(-5,5)
    plt.savefig("im_zx_%d"%i)
    plt.clf()
    
    plt.scatter(l_z, l_y)
    plt.text(7,4, "pt: %s GeV"%pt, fontsize=12)
    plt.xlabel("z (M)")
    plt.ylabel("y (M)")
    plt.hlines(0,0,10)
    plt.xlim(0,10)
    plt.ylim(-5,5)
    plt.savefig("im_zy_%d"%i)
    plt.clf()

('pt: ', 5.5)
('pt: ', 5.518491123104729)
('pt: ', -6.8)
('pt: ', -6.843161983883678)
('pt: ', 2.7)
('pt: ', 2.724614333264909)
('pt: ', 3.7)
('pt: ', 3.7344902231605754)
('pt: ', -52.1)
('pt: ', -52.14000850950842)
('pt: ', -7.2)
('pt: ', -7.218955786347562)
('pt: ', -7.2)
('pt: ', -7.1595091167132825)
('pt: ', 2.6)
('pt: ', 2.619225322213881)
('pt: ', 28.6)
('pt: ', 28.640841460058933)
('pt: ', -4.7)
('pt: ', -4.734953409555779)
('pt: ', 3.5)
('pt: ', 3.5106104255019743)
('pt: ', 11.0)
('pt: ', 11.016212130103815)
('pt: ', 12.8)
('pt: ', 12.772986816821115)
('pt: ', 2.5)
('pt: ', 2.510509790630189)
('pt: ', 2.9)
('pt: ', 2.869510530439561)
('pt: ', 3.5)
('pt: ', 3.4521492938123535)
('pt: ', -11.8)
('pt: ', -11.830459992500726)
('pt: ', -5.7)
('pt: ', -5.732968157611026)
('pt: ', -5.5)
('pt: ', -5.483962712671609)
('pt: ', -3.8)
('pt: ', -3.8197654894084097)
('pt: ', -23.1)
('pt: ', -23.110451905486602)
('pt: ', -9.8)
('pt: ', -9.77935871909945)
('pt: ', 3.7)
('pt: ', 3.69951838743031

('pt: ', -222.1)
('pt: ', -222.05577628602035)
('pt: ', -7.5)
('pt: ', -7.471779553943576)
('pt: ', -5.8)
('pt: ', -5.844500050337926)
('pt: ', -6.3)
('pt: ', -6.274751630729057)
('pt: ', -5.1)
('pt: ', -5.140343007850895)
('pt: ', -58.2)
('pt: ', -58.160279739127965)
('pt: ', -7.3)
('pt: ', -7.343603974870902)
('pt: ', -6.1)
('pt: ', -6.131883317723919)
('pt: ', -5.4)
('pt: ', -5.375216141652439)
('pt: ', 2.3)
('pt: ', 2.2631656689593904)
('pt: ', -14.6)
('pt: ', -14.647216016044768)
('pt: ', -4.5)
('pt: ', -4.536765117465739)
('pt: ', 343.6)
('pt: ', 343.57025537263576)
('pt: ', 3.0)
('pt: ', 2.9832390780972844)
('pt: ', -212.4)
('pt: ', -212.4379743659853)
('pt: ', -6.2)
('pt: ', -6.166943483890414)
('pt: ', 5.9)
('pt: ', 5.8942333028150165)
('pt: ', -4.0)
('pt: ', -3.984791625893758)
('pt: ', -4.5)
('pt: ', -4.5020585308375765)
('pt: ', 2.1)
('pt: ', 2.118303258031444)
('pt: ', 5.9)
('pt: ', 5.859152529217463)
('pt: ', 2.9)
('pt: ', 2.8906269221637606)
('pt: ', -6.3)
('pt: ', -6.25

('pt: ', -2.8)
('pt: ', -2.757560058381875)
('pt: ', -2.2)
('pt: ', -2.1860926322186582)
('pt: ', -15.3)
('pt: ', -15.346884450822762)
('pt: ', -373.7)
('pt: ', -373.7035711976851)
('pt: ', -4.4)
('pt: ', -4.352706046167355)
('pt: ', -9.7)
('pt: ', -9.69753734594097)
('pt: ', -2.4)
('pt: ', -2.4059891249314957)
('pt: ', 2.6)
('pt: ', 2.6412955264174167)
('pt: ', 3.3)
('pt: ', 3.3169135999318318)
('pt: ', -3.4)
('pt: ', -3.449801834805414)
('pt: ', 5.0)
('pt: ', 4.983512322501603)
('pt: ', 5.0)
('pt: ', 4.968342953691757)
('pt: ', -2.7)
('pt: ', -2.708282124236343)
('pt: ', -4.7)
('pt: ', -4.685933714456808)
('pt: ', -8.8)
('pt: ', -8.767730703431225)
('pt: ', 8.4)
('pt: ', 8.438904928235399)
('pt: ', 8.9)
('pt: ', 8.89024095729552)
('pt: ', -2.6)
('pt: ', -2.565304719476065)
('pt: ', -21.2)
('pt: ', -21.210671983699967)
('pt: ', 85.6)
('pt: ', 85.59900981021947)
('pt: ', -15.6)
('pt: ', -15.645424067293947)
('pt: ', -6.7)
('pt: ', -6.705101908583465)
('pt: ', 2.4)
('pt: ', 2.3628111245

('pt: ', -2.7)
('pt: ', -2.7175046381798573)
('pt: ', -3.0)
('pt: ', -2.974352237521049)
('pt: ', 2.2)
('pt: ', 2.1982350929557017)
('pt: ', -2.5)
('pt: ', -2.5448542032859853)
('pt: ', 38.2)
('pt: ', 38.19171272471126)
('pt: ', 4.4)
('pt: ', 4.382835790434076)
('pt: ', 16.2)
('pt: ', 16.164348757930263)
('pt: ', 2.1)
('pt: ', 2.098549371562789)
('pt: ', 7.3)
('pt: ', 7.290376561765016)
('pt: ', -2.2)
('pt: ', -2.223222028338991)
('pt: ', 5.4)
('pt: ', 5.411168612078278)
('pt: ', -5.9)
('pt: ', -5.8526068698785005)
('pt: ', -120.5)
('pt: ', -120.45953280529305)
('pt: ', -6.5)
('pt: ', -6.467921515441063)
('pt: ', -2.1)
('pt: ', -2.1450581192415514)
('pt: ', 8.9)
('pt: ', 8.897813753845128)
('pt: ', -6.9)
('pt: ', -6.947577872475055)
('pt: ', -3.8)
('pt: ', -3.820304324753338)
('pt: ', 4.6)
('pt: ', 4.631016688573106)
('pt: ', -8.2)
('pt: ', -8.216193238929376)
('pt: ', 2.3)
('pt: ', 2.300209459364506)
('pt: ', -13.5)
('pt: ', -13.51035751213557)
('pt: ', -26.3)
('pt: ', -26.27732444068

('pt: ', 16.0)
('pt: ', 16.024419804880104)
('pt: ', -12.1)
('pt: ', -12.078934681483576)
('pt: ', 10.0)
('pt: ', 9.977355287058247)
('pt: ', 2.0)
('pt: ', 2.049070809586895)
('pt: ', -5.1)
('pt: ', -5.10607275337175)
('pt: ', -16.5)
('pt: ', -16.534960230788688)
('pt: ', 2.4)
('pt: ', 2.4395760831268634)
('pt: ', -16.8)
('pt: ', -16.82773601872873)
('pt: ', 2.1)
('pt: ', 2.1183790852248023)
('pt: ', -8.7)
('pt: ', -8.687734855837927)
('pt: ', 17.7)
('pt: ', 17.706249638863962)
('pt: ', -4.6)
('pt: ', -4.609741067745657)
('pt: ', -4.7)
('pt: ', -4.689903384677614)
('pt: ', 3.9)
('pt: ', 3.883336149489273)
('pt: ', 10.5)
('pt: ', 10.528809670540422)
('pt: ', 3.1)
('pt: ', 3.10849762113225)
('pt: ', 4.2)
('pt: ', 4.181540110159993)
('pt: ', -8.9)
('pt: ', -8.8920020182576)
('pt: ', -11.0)
('pt: ', -11.029580352781618)
('pt: ', -3.3)
('pt: ', -3.2575745837505488)
('pt: ', -30.2)
('pt: ', -30.177047069076075)
('pt: ', 4.0)
('pt: ', 3.970145139036706)
('pt: ', 66.5)
('pt: ', 66.520819951627

('pt: ', -12.2)
('pt: ', -12.240441655597461)
('pt: ', -2.5)
('pt: ', -2.48643917357677)
('pt: ', -4.8)
('pt: ', -4.7770266047372445)
('pt: ', -4.6)
('pt: ', -4.645423066345392)
('pt: ', -8.6)
('pt: ', -8.550827893677937)
('pt: ', -8.3)
('pt: ', -8.331753675124762)
('pt: ', -8.1)
('pt: ', -8.145133170205398)
('pt: ', 2.3)
('pt: ', 2.2786164574373995)
('pt: ', 5.1)
('pt: ', 5.129453359630985)
('pt: ', -2.1)
('pt: ', -2.1055400768775154)
('pt: ', 12.4)
('pt: ', 12.398952232925401)
('pt: ', 5.1)
('pt: ', 5.125403744074965)
('pt: ', -3.6)
('pt: ', -3.620015274338798)
('pt: ', 3.4)
('pt: ', 3.4069162535247535)
('pt: ', -26.2)
('pt: ', -26.190853808577952)
('pt: ', 5.4)
('pt: ', 5.368842267288229)
('pt: ', -5.9)
('pt: ', -5.918042672358525)
('pt: ', -4.4)
('pt: ', -4.401552185019699)
('pt: ', 3.2)
('pt: ', 3.2056719619665492)
('pt: ', -38.6)
('pt: ', -38.6438319080024)
('pt: ', -4.6)
('pt: ', -4.645015677452847)
('pt: ', 141.9)
('pt: ', 141.91562158259956)
('pt: ', -2.8)
('pt: ', -2.84795571

<Figure size 432x288 with 0 Axes>

In [122]:
X2

array([[[217,  20],
        [208,  20],
        [208,  20],
        [210,  20]],

       [[242,  15],
        [250,  16],
        [251,  15],
        [252,  16]],

       [[266,  12],
        [251,  12],
        [248,  12],
        [245,  12]],

       ...,

       [[245,  16],
        [237,  15],
        [236,  15],
        [236,  15]],

       [[154,  13],
        [152,  13],
        [151,  13],
        [151,  13]],

       [[270,  12],
        [264,  12],
        [262,  12],
        [261,  12]]])

In [81]:
np.max(X[:,:,0]*1/16)

311

In [82]:
np.min(X[:,:,0]*1/16)

9

In [79]:
th_offset = 10

i=20

print(y[i,2])
print(-log(tan((np.max(X[i,:,1]*1./4+th_offset)/2)*(pi/180))))
print(-log(tan((np.min(X[i,:,1]*1./4+th_offset)/2)*(pi/180))))

1.9623605
1.9158181476670768
1.931069127406849


In [21]:
np.max(X[i,:,1]*1./4+th_offset)

19.5

In [8]:
np.min(X[i,:,1]*1./4+th_offset)

19.0

In [15]:
from math import pi

from numpy import log, tan

-log(tan((np.max(X[i,:,1]*1./4+th_offset)/2)*(pi/180)))

In [19]:
-log(tan((np.min(X[i,:,1]*1./4+th_offset)/2)*(pi/180)))

1.7877120167373686

In [ ]:
X[0,0,0]*(1./16)

In [ ]:
X[0,0,1]*(1./4)